
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: aboreny/panel-backend:latest
    
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: aboreny/panel-frontend:latest
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data: